sudo apt install 0trace
sudo apt install aesfix
sudo apt install aeskeyfind
sudo apt install afflib-tools
sudo apt install libafflib-dev
sudo apt install libafflib0v5
sudo apt install afl++
sudo apt install afl++-doc
sudo apt install aircrack-ng
sudo apt install airgraph-ng
sudo apt install airgeddon
sudo apt install altdns
sudo apt install amap
sudo apt install amass
sudo apt install amass-common
sudo apt install android-sdk
sudo apt install android-sdk-build-tools
sudo apt install android-sdk-build-tools-common
sudo apt install android-sdk-common
sudo apt install android-sdk-platform-tools
sudo apt install android-sdk-platform-tools-common
sudo apt install apache-users
sudo apt install apache2
sudo apt install apache2-bin
sudo apt install apache2-data
sudo apt install apache2-dev
sudo apt install apache2-doc
sudo apt install apache2-ssl-dev
sudo apt install apache2-suexec-custom
sudo apt install apache2-suexec-pristine
sudo apt install apache2-utils
sudo apt install libapache2-mod-md
sudo apt install libapache2-mod-proxy-uwsgi
sudo apt install apktool
sudo apt install apple-bleee
sudo apt install arjun
sudo apt install armitage
sudo apt install arp-scan
sudo apt install arping
sudo apt install arpwatch
sudo apt install asleap
sudo apt install assetfinder
sudo apt install atftp
sudo apt install atftpd
sudo apt install autopsy
sudo apt install axel
sudo apt install b374k
sudo apt install backdoor-factory
sudo apt install bed
sudo apt install beef-xss
sudo apt install berate-ap
sudo apt install bettercap
sudo apt install bettercap-ui
sudo apt install bind9
sudo apt install bind9-dev
sudo apt install bind9-dnsutils
sudo apt install bind9-doc
sudo apt install bind9-host
sudo apt install bind9-libs
sudo apt install bind9-utils
sudo apt install bind9utils
sudo apt install dnsutils
sudo apt install bing-ip2hosts
sudo apt install binwalk
sudo apt install python3-binwalk
sudo apt install bloodhound
sudo apt install bloodhound.py
sudo apt install blue-hydra
sudo apt install bluelog
sudo apt install blueranger
sudo apt install bluesnarfer
sudo apt install bluetooth
sudo apt install bluez
sudo apt install bluez-cups
sudo apt install bluez-hcidump
sudo apt install bluez-meshd
sudo apt install bluez-obexd
sudo apt install bluez-source
sudo apt install bluez-test-scripts
sudo apt install bluez-test-tools
sudo apt install libbluetooth-dev
sudo apt install libbluetooth3
sudo apt install braa
sudo apt install bruteforce-luks
sudo apt install bruteforce-salted-openssl
sudo apt install bruteforce-wallet
sudo apt install bruteshark
sudo apt install brutespray
sudo apt install btscanner
sudo apt install bulk-extractor
sudo apt install bully
sudo apt install burpsuite
sudo apt install bytecode-viewer
sudo apt install cabextract
sudo apt install cadaver
sudo apt install caldera
sudo apt install calicoctl
sudo apt install capstone-tool
sudo apt install libcapstone-dev
sudo apt install libcapstone4
sudo apt install python3-capstone
sudo apt install ccrypt
sudo apt install elpa-ps-ccrypt
sudo apt install certgraph
sudo apt install certipy-ad
sudo apt install cewl
sudo apt install changeme
sudo apt install chaosreader
sudo apt install cherrytree
sudo apt install chirp
sudo apt install chisel
sudo apt install chkrootkit
sudo apt install chntpw
sudo apt install chromium
sudo apt install chromium-common
sudo apt install chromium-driver
sudo apt install chromium-l10n
sudo apt install chromium-sandbox
sudo apt install chromium-shell
sudo apt install cifs-utils
sudo apt install cilium-cli
sudo apt install cisco-auditing-tool
sudo apt install cisco-global-exploiter
sudo apt install cisco-ocs
sudo apt install cisco-torch
sudo apt install cisco7crack
sudo apt install clamav
sudo apt install clamav-base
sudo apt install clamav-daemon
sudo apt install clamav-docs
sudo apt install clamav-freshclam
sudo apt install clamav-milter
sudo apt install clamav-testfiles
sudo apt install clamdscan
sudo apt install libclamav-dev
sudo apt install libclamav11
sudo apt install cloud-enum
sudo apt install cloudbrute
sudo apt install cmospwd
sudo apt install cmseek
sudo apt install cntlm
sudo apt install code-oss
sudo apt install colly
sudo apt install golang-github-gocolly-colly-dev
sudo apt install command-not-found
sudo apt install commix
sudo apt install copy-router-config
sudo apt install cosign
sudo apt install covenant-kbx
sudo apt install cowpatty
sudo apt install crack
sudo apt install crack-common
sudo apt install crack-md5
sudo apt install crackle
sudo apt install crackmapexec
sudo apt install creddump7
sudo apt install cri-tools
sudo apt install crowbar
sudo apt install crunch
sudo apt install cryptcat
sudo apt install cryptsetup
sudo apt install cryptsetup-bin
sudo apt install cryptsetup-initramfs
sudo apt install cryptsetup-ssh
sudo apt install cryptsetup-suspend
sudo apt install libcryptsetup-dev
sudo apt install libcryptsetup12
sudo apt install cryptsetup-nuke-password
sudo apt install cupid-hostapd
sudo apt install cupid-wpasupplicant
sudo apt install curl
sudo apt install libcurl3-gnutls
sudo apt install libcurl4
sudo apt install libcurl4-doc
sudo apt install libcurl4-gnutls-dev
sudo apt install libcurl4-openssl-dev
sudo apt install curlftpfs
sudo apt install cutecom
sudo apt install cutycapt
sudo apt install cymothoa
sudo apt install darkstat
sudo apt install davtest
sudo apt install dbd
sudo apt install dbeaver
sudo apt install dc3dd
sudo apt install dcfldd
sudo apt install ddrescue
sudo apt install de4dot
sudo apt install defectdojo
sudo apt install dex2jar
sudo apt install python3-dfdatetime
sudo apt install python3-dfvfs
sudo apt install python3-dfwinreg
sudo apt install dhcpig
sudo apt install dirb
sudo apt install dirbuster
sudo apt install dirsearch
sudo apt install dislocker
sudo apt install libdislocker0-dev
sudo apt install libdislocker0.7
sudo apt install libdistorm3-3
sudo apt install libdistorm3-dev
sudo apt install python3-distorm3
sudo apt install dmitry
sudo apt install dns2tcp
sudo apt install dnscat2
sudo apt install dnscat2-client
sudo apt install dnscat2-server
sudo apt install dnschef
sudo apt install dnsenum
sudo apt install dnsgen
sudo apt install dnsmap
sudo apt install dnsrecon
sudo apt install dnstracer
sudo apt install dnstwist
sudo apt install dnswalk
sudo apt install dnsx
sudo apt install doona
sudo apt install dos2unix
sudo apt install dotdotpwn
sudo apt install dradis
sudo apt install driftnet
sudo apt install dscan
sudo apt install dscan-doc
sudo apt install dsniff
sudo apt install dufflebag
sudo apt install dumpsterdiver
sudo apt install dumpzilla
sudo apt install dvwa
sudo apt install dwarf2json
sudo apt install eaphammer
sudo apt install eapmd5pass
sudo apt install edb-debugger
sudo apt install edb-debugger-plugins
sudo apt install eksctl
sudo apt install email2phonenumber
sudo apt install emailharvester
sudo apt install enum4linux
sudo apt install enum4linux-ng
sudo apt install enumiax
sudo apt install ethtool
sudo apt install ettercap-common
sudo apt install ettercap-graphical
sudo apt install ettercap-text-only
sudo apt install evil-ssdp
sudo apt install evil-winrm
sudo apt install evilginx2
sudo apt install exe2hexbat
sudo apt install exiflooter
sudo apt install exifprobe
sudo apt install exiv2
sudo apt install libexiv2-27
sudo apt install libexiv2-dev
sudo apt install libexiv2-doc
sudo apt install expect
sudo apt install tcl-expect
sudo apt install tcl-expect-dev
sudo apt install exploitdb
sudo apt install exploitdb-bin-sploits
sudo apt install exploitdb-papers
sudo apt install ext3grep
sudo apt install ext4magic
sudo apt install extundelete
sudo apt install eyewitness
sudo apt install faraday-agent-dispatcher
sudo apt install faraday-cli
sudo apt install fatcat
sudo apt install fcrackzip
sudo apt install fern-wifi-cracker
sudo apt install feroxbuster
sudo apt install ferret-sidejack
sudo apt install ffuf
sudo apt install fierce
sudo apt install fiked
sudo apt install finalrecon
sudo apt install firefox-developer-edition-en-us-kbx
sudo apt install firewalk
sudo apt install firmware-mod-kit
sudo apt install flashrom
sudo apt install libflashrom-dev
sudo apt install libflashrom1
sudo apt install foremost
sudo apt install forensic-artifacts
sudo apt install python3-artifacts
sudo apt install forensics-colorize
sudo apt install fping
sudo apt install fragrouter
sudo apt install framework2
sudo apt install freeradius
sudo apt install freeradius-common
sudo apt install freeradius-config
sudo apt install freeradius-dhcp
sudo apt install freeradius-iodbc
sudo apt install freeradius-krb5
sudo apt install freeradius-ldap
sudo apt install freeradius-memcached
sudo apt install freeradius-mysql
sudo apt install freeradius-postgresql
sudo apt install freeradius-python3
sudo apt install freeradius-redis
sudo apt install freeradius-rest
sudo apt install freeradius-utils
sudo apt install freeradius-yubikey
sudo apt install libfreeradius-dev
sudo apt install libfreeradius3
sudo apt install freeradius-wpe
sudo apt install freerdp2-dev
sudo apt install freerdp2-shadow-x11
sudo apt install freerdp2-wayland
sudo apt install freerdp2-x11
sudo apt install libfreerdp-client2-2
sudo apt install libfreerdp-server2-2
sudo apt install libfreerdp-shadow-subsystem2-2
sudo apt install libfreerdp-shadow2-2
sudo apt install libfreerdp2-2
sudo apt install libuwac0-0
sudo apt install libuwac0-dev
sudo apt install libwinpr-tools2-2
sudo apt install libwinpr2-2
sudo apt install libwinpr2-dev
sudo apt install winpr-utils
sudo apt install ftester
sudo apt install fuse3
sudo apt install libfuse3-3
sudo apt install libfuse3-dev
sudo apt install fwbuilder
sudo apt install fwbuilder-common
sudo apt install fwbuilder-doc
sudo apt install galleta
sudo apt install gdb-peda
sudo apt install gdisk
sudo apt install getallurls
sudo apt install ghidra
sudo apt install git
sudo apt install git-all
sudo apt install git-cvs
sudo apt install git-daemon-run
sudo apt install git-daemon-sysvinit
sudo apt install git-doc
sudo apt install git-email
sudo apt install git-gui
sudo apt install git-man
sudo apt install git-mediawiki
sudo apt install git-svn
sudo apt install gitk
sudo apt install gitweb
sudo apt install gitleaks
sudo apt install glibc-doc
sudo apt install glibc-source
sudo apt install libc-bin
sudo apt install libc-dev-bin
sudo apt install libc-devtools
sudo apt install libc-l10n
sudo apt install libc0.3
sudo apt install libc0.3-dev
sudo apt install libc6
sudo apt install libc6-amd64
sudo apt install libc6-dbg
sudo apt install libc6-dev
sudo apt install libc6-dev-i386
sudo apt install libc6-dev-x32
sudo apt install libc6-i386
sudo apt install libc6-mips32
sudo apt install libc6-mips64
sudo apt install libc6-mipsn32
sudo apt install libc6-powerpc
sudo apt install libc6-ppc64
sudo apt install libc6-s390
sudo apt install libc6-sparc
sudo apt install libc6-sparc64
sudo apt install libc6-x32
sudo apt install libc6.1
sudo apt install libc6.1-dev
sudo apt install locales
sudo apt install locales-all
sudo apt install nscd
sudo apt install gnuradio
sudo apt install gnuradio-dev
sudo apt install gnuradio-doc
sudo apt install libgnuradio-analog3.10.8
sudo apt install libgnuradio-audio3.10.8
sudo apt install libgnuradio-blocks3.10.8
sudo apt install libgnuradio-channels3.10.8
sudo apt install libgnuradio-digital3.10.8
sudo apt install libgnuradio-dtv3.10.8
sudo apt install libgnuradio-fec3.10.8
sudo apt install libgnuradio-fft3.10.8
sudo apt install libgnuradio-filter3.10.8
sudo apt install libgnuradio-iio3.10.8
sudo apt install libgnuradio-network3.10.8
sudo apt install libgnuradio-pdu3.10.8
sudo apt install libgnuradio-pmt3.10.8
sudo apt install libgnuradio-qtgui3.10.8
sudo apt install libgnuradio-runtime3.10.8
sudo apt install libgnuradio-soapy3.10.8
sudo apt install libgnuradio-trellis3.10.8
sudo apt install libgnuradio-uhd3.10.8
sudo apt install libgnuradio-video-sdl3.10.8
sudo apt install libgnuradio-vocoder3.10.8
sudo apt install libgnuradio-wavelet3.10.8
sudo apt install libgnuradio-zeromq3.10.8
sudo apt install gobuster
sudo apt install godoh
sudo apt install golang-github-binject-go-donut
sudo apt install golang-github-binject-go-donut-dev
sudo apt install goldeneye
sudo apt install goofile
sudo apt install google-nexus-tools
sudo apt install gophish
sudo apt install gospider
sudo apt install gpart
sudo apt install gparted
sudo apt install gparted-common
sudo apt install gpp-decrypt
sudo apt install gqrx-sdr
sudo apt install gr-air-modes
sudo apt install libgnuradio-air-modes1
sudo apt install gr-iqbal
sudo apt install libgnuradio-iqbalance3.9.0
sudo apt install gr-osmosdr
sudo apt install libgnuradio-osmosdr0.2.0
sudo apt install grokevt
sudo apt install gss-ntlmssp
sudo apt install gss-ntlmssp-dev
sudo apt install caja-gtkhash
sudo apt install gtkhash
sudo apt install nemo-gtkhash
sudo apt install thunar-gtkhash
sudo apt install guymager
sudo apt install gvm
sudo apt install h8mail
sudo apt install hackrf
sudo apt install hackrf-doc
sudo apt install libhackrf-dev
sudo apt install libhackrf0
sudo apt install hak5-wifi-coconut
sudo apt install hakrawler
sudo apt install hamster-sidejack
sudo apt install hash-identifier
sudo apt install hashcat
sudo apt install hashcat-data
sudo apt install hashcat-utils
sudo apt install hashdeep
sudo apt install hashid
sudo apt install hashrat
sudo apt install havoc
sudo apt install hb-honeypot
sudo apt install hcxtools
sudo apt install heartleech
sudo apt install hexinject
sudo apt install libhivex-bin
sudo apt install libhivex-dev
sudo apt install libhivex-ocaml
sudo apt install libhivex-ocaml-dev
sudo apt install libhivex0
sudo apt install libwin-hivex-perl
sudo apt install python3-hivex
sudo apt install ruby-hivex
sudo apt install hostapd-mana
sudo apt install hostapd-wpe
sudo apt install hosthunter
sudo apt install hostsman
sudo apt install hotpatch
sudo apt install hping3
sudo apt install htshells
sudo apt install httprint
sudo apt install httprobe
sudo apt install httpx-toolkit
sudo apt install httrack
sudo apt install httrack-doc
sudo apt install libhttrack-dev
sudo apt install libhttrack2
sudo apt install proxytrack
sudo apt install webhttrack
sudo apt install webhttrack-common
sudo apt install hubble
sudo apt install humble
sudo apt install hurl
sudo apt install hydra
sudo apt install hydra-gtk
sudo apt install hyperion
sudo apt install i2c-tools
sudo apt install libi2c-dev
sudo apt install libi2c0
sudo apt install python3-smbus
sudo apt install iaxflood
sudo apt install ibombshell
sudo apt install ident-user-enum
sudo apt install ifenslave
sudo apt install ike-scan
sudo apt install imhex
sudo apt install python3-impacket
sudo apt install impacket-scripts
sudo apt install inetsim
sudo apt install inspectrum
sudo apt install inspy
sudo apt install instaloader
sudo apt install intrace
sudo apt install inviteflood
sudo apt install iodine
sudo apt install ipv6toolkit
sudo apt install irpas
sudo apt install ismtp
sudo apt install isr-evilgrade
sudo apt install ivre
sudo apt install ivre-doc
sudo apt install iw
sudo apt install jadx
sudo apt install javasnoop
sudo apt install jboss-autopwn
sudo apt install jd-gui
sudo apt install john
sudo apt install john-data
sudo apt install johnny
sudo apt install joomscan
sudo apt install joplin
sudo apt install joplin-cli
sudo apt install jsp-file-browser
sudo apt install jsql-injection
sudo apt install juice-shop
sudo apt install kali-autopilot
sudo apt install kali-community-wallpapers
sudo apt install kali-defaults
sudo apt install kali-defaults-desktop
sudo apt install kali-desktop-core
sudo apt install kali-desktop-e17
sudo apt install kali-desktop-gnome
sudo apt install kali-desktop-i3
sudo apt install kali-desktop-i3-gaps
sudo apt install kali-desktop-kde
sudo apt install kali-desktop-live
sudo apt install kali-desktop-lxde
sudo apt install kali-desktop-mate
sudo apt install kali-desktop-xfce
sudo apt install kali-linux-core
sudo apt install kali-linux-default
sudo apt install kali-linux-everything
sudo apt install kali-linux-firmware
sudo apt install kali-linux-headless
sudo apt install kali-linux-labs
sudo apt install kali-linux-large
sudo apt install kali-linux-nethunter
sudo apt install kali-linux-wsl
sudo apt install kali-system-cli
sudo apt install kali-system-core
sudo apt install kali-system-gui
sudo apt install kali-tools-802-11
sudo apt install kali-tools-bluetooth
sudo apt install kali-tools-crypto-stego
sudo apt install kali-tools-database
sudo apt install kali-tools-detect
sudo apt install kali-tools-exploitation
sudo apt install kali-tools-forensics
sudo apt install kali-tools-fuzzing
sudo apt install kali-tools-gpu
sudo apt install kali-tools-hardware
sudo apt install kali-tools-identify
sudo apt install kali-tools-information-gathering
sudo apt install kali-tools-passwords
sudo apt install kali-tools-post-exploitation
sudo apt install kali-tools-protect
sudo apt install kali-tools-recover
sudo apt install kali-tools-reporting
sudo apt install kali-tools-respond
sudo apt install kali-tools-reverse-engineering
sudo apt install kali-tools-rfid
sudo apt install kali-tools-sdr
sudo apt install kali-tools-sniffing-spoofing
sudo apt install kali-tools-social-engineering
sudo apt install kali-tools-top10
sudo apt install kali-tools-voip
sudo apt install kali-tools-vulnerability
sudo apt install kali-tools-web
sudo apt install kali-tools-windows-resources
sudo apt install kali-tools-wireless
sudo apt install kali-tweaks
sudo apt install kali-legacy-wallpapers
sudo apt install kali-wallpapers-2019.4
sudo apt install kali-wallpapers-2020.4
sudo apt install kali-wallpapers-2021.4
sudo apt install kali-wallpapers-2022
sudo apt install kali-wallpapers-2023
sudo apt install kali-wallpapers-all
sudo apt install kali-wallpapers-legacy
sudo apt install kali-wallpapers-mobile-2023
sudo apt install kalibrate-rtl
sudo apt install kerberoast
sudo apt install kismet
sudo apt install kismet-capture-common
sudo apt install kismet-capture-hak5-wifi-coconut
sudo apt install kismet-capture-linux-bluetooth
sudo apt install kismet-capture-linux-wifi
sudo apt install kismet-capture-nrf-51822
sudo apt install kismet-capture-nrf-52840
sudo apt install kismet-capture-nrf-mousejack
sudo apt install kismet-capture-nxp-kw41z
sudo apt install kismet-capture-rz-killerbee
sudo apt install kismet-capture-ti-cc-2531
sudo apt install kismet-capture-ti-cc-2540
sudo apt install kismet-capture-ubertooth-one
sudo apt install kismet-core
sudo apt install kismet-logtools
sudo apt install kismet-plugins
sudo apt install python3-kismetcapturebtgeiger
sudo apt install python3-kismetcapturefreaklabszigbee
sudo apt install python3-kismetcapturertl433
sudo apt install python3-kismetcapturertladsb
sudo apt install python3-kismetcapturertlamr
sudo apt install knocker
sudo apt install koadic
sudo apt install kubernetes-helm
sudo apt install kustomize
sudo apt install lapsdumper
sudo apt install laudanum
sudo apt install lbd
sudo apt install legion
sudo apt install ewf-tools
sudo apt install libewf-dev
sudo apt install libewf2
sudo apt install python3-libewf
sudo apt install libfindrtp
sudo apt install libfreefare-bin
sudo apt install libfreefare-dev
sudo apt install libfreefare-doc
sudo apt install libfreefare0
sudo apt install libimage-exiftool-perl
sudo apt install libnfc-bin
sudo apt install libnfc-dev
sudo apt install libnfc-examples
sudo apt install libnfc-pn53x-examples
sudo apt install libnfc6
sudo apt install libpst-dev
sudo apt install libpst4
sudo apt install pst-utils
sudo apt install libsmali-java
sudo apt install linux-exploit-suggester
sudo apt install clang
sudo apt install clang-format
sudo apt install clang-tidy
sudo apt install clang-tools
sudo apt install clangd
sudo apt install flang
sudo apt install libbolt-dev
sudo apt install libc++-dev
sudo apt install libc++-dev-wasm32
sudo apt install libc++1
sudo apt install libc++abi-dev
sudo apt install libc++abi1
sudo apt install libclang-cpp-dev
sudo apt install libclang-dev
sudo apt install libclang-rt-dev
sudo apt install libclang-rt-dev-wasm32
sudo apt install libclang-rt-dev-wasm64
sudo apt install libclang1
sudo apt install libflang-dev
sudo apt install liblld-dev
sudo apt install liblldb-dev
sudo apt install libllvm-ocaml-dev
sudo apt install libomp-dev
sudo apt install libomp5
sudo apt install lld
sudo apt install lldb
sudo apt install llvm
sudo apt install llvm-bolt
sudo apt install llvm-dev
sudo apt install llvm-runtime
sudo apt install python3-clang
sudo apt install python3-lldb
sudo apt install dmeventd
sudo apt install dmsetup
sudo apt install libdevmapper-dev
sudo apt install libdevmapper-event1.02.1
sudo apt install libdevmapper1.02.1
sudo apt install liblvm2-dev
sudo apt install liblvm2cmd2.03
sudo apt install lvm2
sudo apt install lvm2-dbusd
sudo apt install lvm2-lockd
sudo apt install lynis
sudo apt install mac-robber
sudo apt install macchanger
sudo apt install magicrescue
sudo apt install maltego
sudo apt install maltego-teeth
sudo apt install maryam
sudo apt install maskprocessor
sudo apt install masscan
sudo apt install massdns
sudo apt install mc
sudo apt install mc-data
sudo apt install libmdb3
sudo apt install libmdbsql3
sudo apt install mdbtools
sudo apt install mdbtools-dev
sudo apt install mdbtools-doc
sudo apt install odbc-mdbtools
sudo apt install mdk3
sudo apt install mdk4
sudo apt install medusa
sudo apt install memdump
sudo apt install mercurial
sudo apt install mercurial-common
sudo apt install golang-github-ne0nd0g-merlin-dev
sudo apt install merlin
sudo apt install merlin-server
sudo apt install merlin-agent
sudo apt install metacam
sudo apt install metagoofil
sudo apt install metasploit-framework
sudo apt install mfcuk
sudo apt install mfoc
sudo apt install mfterm
sudo apt install mimikatz
sudo apt install minicom
sudo apt install miredo
sudo apt install miredo-server
sudo apt install missidentify
sudo apt install mitmproxy
sudo apt install mongo-tools
sudo apt install msfpc
sudo apt install multiforcer
sudo apt install multimac
sudo apt install multimon-ng
sudo apt install myrescue
sudo apt install default-libmysqlclient-dev
sudo apt install default-libmysqld-dev
sudo apt install default-mysql-client
sudo apt install default-mysql-client-core
sudo apt install default-mysql-server
sudo apt install default-mysql-server-core
sudo apt install mysql-common
sudo apt install naabu
sudo apt install name-that-hash
sudo apt install nasm
sudo apt install nasty
sudo apt install nbtscan
sudo apt install nbtscan-unixwiz
sudo apt install ncat-w32
sudo apt install ncrack
sudo apt install ncurses-hexedit
sudo apt install libnetsnmptrapd40
sudo apt install libsnmp-base
sudo apt install libsnmp-dev
sudo apt install libsnmp-perl
sudo apt install libsnmp40
sudo apt install snmp
sudo apt install snmpd
sudo apt install snmptrapd
sudo apt install tkmib
sudo apt install net-tools
sudo apt install netbase
sudo apt install netcat-traditional
sudo apt install netdiscover
sudo apt install netmask
sudo apt install netsed
sudo apt install netsniff-ng
sudo apt install netwag
sudo apt install netwag-doc
sudo apt install netwox
sudo apt install netwox-doc
sudo apt install nextnet
sudo apt install libnfsidmap-dev
sudo apt install libnfsidmap1
sudo apt install nfs-common
sudo apt install nfs-kernel-server
sudo apt install ngrep
sudo apt install nikto
sudo apt install nipper-ng
sudo apt install nishang
sudo apt install ncat
sudo apt install ndiff
sudo apt install nmap
sudo apt install nmap-common
sudo apt install nmapsi4
sudo apt install nuclei
sudo apt install o-saft
sudo apt install oclgausscrack
sudo apt install odat
sudo apt install offsec-awae
sudo apt install offsec-awae-python2
sudo apt install offsec-exp100
sudo apt install offsec-exp301
sudo apt install offsec-pen300
sudo apt install offsec-pwk
sudo apt install ohrwurm
sudo apt install ollydbg
sudo apt install onesixtyone
sudo apt install openocd
sudo apt install openssh-client
sudo apt install openssh-server
sudo apt install openssh-sftp-server
sudo apt install openssh-tests
sudo apt install ssh
sudo apt install ssh-askpass-gnome
sudo apt install openvpn
sudo apt install ophcrack
sudo apt install ophcrack-cli
sudo apt install oscanner
sudo apt install osrframework
sudo apt install outguess
sudo apt install owasp-mantra-ff
sudo apt install owl
sudo apt install p0f
sudo apt install p7zip
sudo apt install p7zip-full
sudo apt install pack
sudo apt install pack2
sudo apt install pacu
sudo apt install padbuster
sudo apt install paros
sudo apt install parsero
sudo apt install libparted-dev
sudo apt install libparted-fs-resize0
sudo apt install libparted-i18n
sudo apt install libparted2
sudo apt install parted
sudo apt install parted-doc
sudo apt install pasco
sudo apt install passdetective
sudo apt install passing-the-hash
sudo apt install patator
sudo apt install payloadsallthethings
sudo apt install pdf-parser
sudo apt install pdfcrack
sudo apt install pdfid
sudo apt install peass
sudo apt install peirates
sudo apt install perl-cisco-copyconfig
sudo apt install pev
sudo apt install phishery
sudo apt install photon
sudo apt install libapache2-mod-php
sudo apt install libphp-embed
sudo apt install php
sudo apt install php-all-dev
sudo apt install php-bcmath
sudo apt install php-bz2
sudo apt install php-cgi
sudo apt install php-cli
sudo apt install php-common
sudo apt install php-curl
sudo apt install php-dev
sudo apt install php-enchant
sudo apt install php-fpm
sudo apt install php-gd
sudo apt install php-gmp
sudo apt install php-imap
sudo apt install php-interbase
sudo apt install php-intl
sudo apt install php-json
sudo apt install php-ldap
sudo apt install php-mbstring
sudo apt install php-mysql
sudo apt install php-odbc
sudo apt install php-pgsql
sudo apt install php-phpdbg
sudo apt install php-pspell
sudo apt install php-readline
sudo apt install php-snmp
sudo apt install php-soap
sudo apt install php-sqlite3
sudo apt install php-sybase
sudo apt install php-tidy
sudo apt install php-xml
sudo apt install php-zip
sudo apt install phpggc
sudo apt install phpsploit
sudo apt install pipal
sudo apt install pixiewps
sudo apt install plaso
sudo apt install python3-plaso
sudo apt install plocate
sudo apt install pnscan
sudo apt install pocsuite3
sudo apt install polenum
sudo apt install pompem
sudo apt install portspoof
sudo apt install poshc2
sudo apt install powercat
sudo apt install powershell
sudo apt install powershell-empire
sudo apt install powersploit
sudo apt install princeprocessor
sudo apt install protos-sip
sudo apt install proxify
sudo apt install proxmark3
sudo apt install proxmark3-common
sudo apt install proxmark3-doc
sudo apt install proxmark3-firmwares
sudo apt install libproxychains4
sudo apt install proxychains4
sudo apt install proxytunnel
sudo apt install pskracker
sudo apt install pskracker-data
sudo apt install ptunnel
sudo apt install pwnat
sudo apt install pwncat
sudo apt install libpython-all-dbg
sudo apt install libpython-all-dev
sudo apt install libpython2-dbg
sudo apt install libpython2-dev
sudo apt install libpython2-stdlib
sudo apt install python-all
sudo apt install python-all-dbg
sudo apt install python-all-dev
sudo apt install python2
sudo apt install python2-dbg
sudo apt install python2-dev
sudo apt install python2-doc
sudo apt install python2-minimal
sudo apt install faraday
sudo apt install python-faraday
sudo apt install python3-ldapdomaindump
sudo apt install python3-pip
sudo apt install python3-pip-whl
sudo apt install python3-virtualenv
sudo apt install virtualenv
sudo apt install qemu-block-extra
sudo apt install qemu-guest-agent
sudo apt install qemu-system
sudo apt install qemu-system-arm
sudo apt install qemu-system-common
sudo apt install qemu-system-data
sudo apt install qemu-system-gui
sudo apt install qemu-system-mips
sudo apt install qemu-system-misc
sudo apt install qemu-system-modules-opengl
sudo apt install qemu-system-modules-spice
sudo apt install qemu-system-ppc
sudo apt install qemu-system-sparc
sudo apt install qemu-system-x86
sudo apt install qemu-system-xen
sudo apt install qemu-user
sudo apt install qemu-user-binfmt
sudo apt install qemu-user-static
sudo apt install qemu-utils
sudo apt install qsslcaudit
sudo apt install quark-engine
sudo apt install libradare2-5.0.0
sudo apt install libradare2-common
sudo apt install libradare2-dev
sudo apt install radare2
sudo apt install rainbowcrack
sudo apt install rake
sudo apt install rarcrack
sudo apt install raven
sudo apt install rcracki-mt
sudo apt install rdesktop
sudo apt install reaver
sudo apt install rebind
sudo apt install recon-ng
sudo apt install reconspider
sudo apt install recordmydesktop
sudo apt install recoverdm
sudo apt install recoverjpeg
sudo apt install redeye
sudo apt install redfang
sudo apt install redsnarf
sudo apt install redsocks
sudo apt install libregfi-dev
sudo apt install libregfi1
sudo apt install python3-pyregfi
sudo apt install reglookup
sudo apt install reglookup-doc
sudo apt install regripper
sudo apt install rekono-kbx
sudo apt install rephrase
sudo apt install python-requests-doc
sudo apt install python3-requests
sudo apt install responder
sudo apt install rev-proxy-grapher
sudo apt install rfcat
sudo apt install rfdump
sudo apt install ridenum
sudo apt install rifiuti
sudo apt install rifiuti2
sudo apt install librizin-cutter-dev
sudo apt install rizin-cutter
sudo apt install rkhunter
sudo apt install rling
sudo apt install golang-github-temoto-robotstxt-dev
sudo apt install robotstxt
sudo apt install ropper
sudo apt install routerkeygenpc
sudo apt install routersploit
sudo apt install rsakeyfind
sudo apt install rsmangler
sudo apt install rtlsdr-scanner
sudo apt install rtpbreak
sudo apt install rtpflood
sudo apt install rtpinsertsound
sudo apt install rtpmixsound
sudo apt install ruby-pedump
sudo apt install rz-ghidra
sudo apt install s3scanner
sudo apt install safecopy
sudo apt install sakis3g
sudo apt install ctdb
sudo apt install ldb-tools
sudo apt install libldb-dev
sudo apt install libldb2
sudo apt install libnss-winbind
sudo apt install libpam-winbind
sudo apt install libsmbclient
sudo apt install libsmbclient-dev
sudo apt install libwbclient-dev
sudo apt install libwbclient0
sudo apt install python3-ldb
sudo apt install python3-ldb-dev
sudo apt install python3-samba
sudo apt install registry-tools
sudo apt install samba
sudo apt install samba-ad-dc
sudo apt install samba-ad-provision
sudo apt install samba-common
sudo apt install samba-common-bin
sudo apt install samba-dev
sudo apt install samba-dsdb-modules
sudo apt install samba-libs
sudo apt install samba-testsuite
sudo apt install samba-vfs-modules
sudo apt install smbclient
sudo apt install winbind
sudo apt install samdump2
sudo apt install sbd
sudo apt install scalpel
sudo apt install python3-scapy
sudo apt install screen
sudo apt install scrounge-ntfs
sudo apt install sctpscan
sudo apt install seclists
sudo apt install secure-socket-funneling-windows-binaries
sudo apt install sendemail
sudo apt install sentrypeer
sudo apt install set
sudo apt install sfuzz
sudo apt install shed
sudo apt install shellfire
sudo apt install shellnoob
sudo apt install shellter
sudo apt install sherlock
sudo apt install sidguesser
sudo apt install siege
sudo apt install sigma-cli
sudo apt install silenttrinity
sudo apt install siparmyknife
sudo apt install sipcrack
sudo apt install sipp
sudo apt install sipsak
sudo apt install sipvicious
sudo apt install skipfish
sudo apt install libtsk-dev
sudo apt install libtsk19
sudo apt install sleuthkit
sudo apt install slimtoolkit
sudo apt install sliver
sudo apt install slowhttptest
sudo apt install smbmap
sudo apt install smtp-user-enum
sudo apt install sn0int
sudo apt install sniffjoke
sudo apt install snmpcheck
sudo apt install snmpenum
sudo apt install snowdrop
sudo apt install socat
sudo apt install sparrow-wifi
sudo apt install spectools
sudo apt install spiderfoot
sudo apt install spike
sudo apt install spire
sudo apt install spooftooph
sudo apt install spray
sudo apt install sprayingtoolkit
sudo apt install spraykatz
sudo apt install sqldict
sudo apt install sqlitebrowser
sudo apt install sqlmap
sudo apt install sqlninja
sudo apt install sqlsus
sudo apt install libfuzzy-dev
sudo apt install libfuzzy2
sudo apt install ssdeep
sudo apt install ssldump
sudo apt install sslh
sudo apt install sslscan
sudo apt install sslsniff
sudo apt install sslsplit
sudo apt install sslstrip
sudo apt install sslyze
sudo apt install statsprocessor
sudo apt install stegcracker
sudo apt install steghide
sudo apt install steghide-doc
sudo apt install stegsnow
sudo apt install stunnel4
sudo apt install subfinder
sudo apt install subjack
sudo apt install sublist3r
sudo apt install libapache2-mod-svn
sudo apt install libsvn-dev
sudo apt install libsvn-doc
sudo apt install libsvn-java
sudo apt install libsvn-perl
sudo apt install libsvn1
sudo apt install python3-subversion
sudo apt install ruby-svn
sudo apt install subversion
sudo apt install subversion-tools
sudo apt install sucrack
sudo apt install libnss-sudo
sudo apt install sudo
sudo apt install sudo-ldap
sudo apt install swaks
sudo apt install syft
sudo apt install t50
sudo apt install tcpdump
sudo apt install tcpflow
sudo apt install tcpflow-nox
sudo apt install tcpick
sudo apt install tcpreplay
sudo apt install teamsploit
sudo apt install termineter
sudo apt install terraform
sudo apt install testdisk
sudo apt install testssl.sh
sudo apt install tetragon
sudo apt install tftp-hpa
sudo apt install tftp-hpa-dbg
sudo apt install tftpd-hpa
sudo apt install tftpd32
sudo apt install thc-ipv6
sudo apt install thc-pptp-bruter
sudo apt install thc-ssl-dos
sudo apt install theharvester
sudo apt install tiger
sudo apt install tiger-otheros
sudo apt install tightvncpasswd
sudo apt install tightvncserver
sudo apt install xtightvncviewer
sudo apt install tlssled
sudo apt install tmux
sudo apt install ftp
sudo apt install tnftp
sudo apt install tnscmd10g
sudo apt install traceroute
sudo apt install trivy
sudo apt install truecrack
sudo apt install trufflehog
sudo apt install tundeep
sudo apt install twofi
sudo apt install tzdata
sudo apt install tzdata-legacy
sudo apt install libubertooth-dev
sudo apt install libubertooth1
sudo apt install ubertooth
sudo apt install ubertooth-firmware
sudo apt install ubertooth-firmware-source
sudo apt install udptunnel
sudo apt install libuhd-dev
sudo apt install libuhd4.5.0
sudo apt install libuhd4.5.0-dpdk
sudo apt install libuhd4.5.0-dpdk-tests
sudo apt install python3-uhd
sudo apt install uhd-doc
sudo apt install uhd-host
sudo apt install uhd-images
sudo apt install unar
sudo apt install unblob
sudo apt install undbx
sudo apt install unhide
sudo apt install unhide-gui
sudo apt install unhide.rb
sudo apt install unicorn-magic
sudo apt install unicornscan
sudo apt install uniscan
sudo apt install unix-privesc-check
sudo apt install libunrar-dev
sudo apt install libunrar-headers
sudo apt install libunrar5
sudo apt install unrar
sudo apt install upx-ucl
sudo apt install urlcrazy
sudo apt install bsdextrautils
sudo apt install bsdutils
sudo apt install eject
sudo apt install fdisk
sudo apt install libblkid-dev
sudo apt install libblkid1
sudo apt install libfdisk-dev
sudo apt install libfdisk1
sudo apt install libmount-dev
sudo apt install libmount1
sudo apt install libsmartcols-dev
sudo apt install libsmartcols1
sudo apt install libuuid1
sudo apt install mount
sudo apt install rfkill
sudo apt install util-linux
sudo apt install util-linux-extra
sudo apt install util-linux-locales
sudo apt install uuid-dev
sudo apt install uuid-runtime
sudo apt install cgpt
sudo apt install vboot-kernel-utils
sudo apt install vboot-utils
sudo apt install veil
sudo apt install veil-catapult
sudo apt install veil-evasion
sudo apt install villain
sudo apt install vim
sudo apt install vim-athena
sudo apt install vim-common
sudo apt install vim-doc
sudo apt install vim-gtk3
sudo apt install vim-gui-common
sudo apt install vim-motif
sudo apt install vim-nox
sudo apt install vim-runtime
sudo apt install vim-tiny
sudo apt install xxd
sudo apt install vinetto
sudo apt install vlan
sudo apt install voiphopper
sudo apt install vpnc
sudo apt install wafw00f
sudo apt install wapiti
sudo apt install watobo
sudo apt install wce
sudo apt install webacoo
sudo apt install webscarab
sudo apt install webshells
sudo apt install websploit
sudo apt install weevely
sudo apt install wfuzz
sudo apt install wget
sudo apt install wgetpaste
sudo apt install python-dev-is-python3
sudo apt install python-is-python3
sudo apt install whatmask
sudo apt install whatweb
sudo apt install whois
sudo apt install wifi-honey
sudo apt install wifiphisher
sudo apt install wifipumpkin3
sudo apt install wifite
sudo apt install wig
sudo apt install wig-ng
sudo apt install windows-binaries
sudo apt install windows-privesc-check
sudo apt install winexe
sudo apt install winregfs
sudo apt install libwireshark-data
sudo apt install libwireshark-dev
sudo apt install libwireshark17
sudo apt install libwiretap-dev
sudo apt install libwiretap14
sudo apt install libwsutil-dev
sudo apt install libwsutil15
sudo apt install tshark
sudo apt install wireshark
sudo apt install wireshark-common
sudo apt install wireshark-dev
sudo apt install wireshark-doc
sudo apt install witnessme
sudo apt install wmi-client
sudo apt install wordlistraider
sudo apt install wordlists
sudo apt install wotmate
sudo apt install wpa-sycophant
sudo apt install wpscan
sudo apt install python-wsgidav-doc
sudo apt install python3-wsgidav
sudo apt install xmount
sudo apt install xplico
sudo apt install xspy
sudo apt install xsser
sudo apt install libyara-dev
sudo apt install libyara10
sudo apt install yara
sudo apt install yara-doc
sudo apt install yersinia
sudo apt install zaproxy
sudo apt install zenmap-kbx
sudo apt install zerofree
sudo apt install zim
sudo apt install golang-github-zonedb-zonedb-dev
sudo apt install zonedb
sudo apt install zsh
sudo apt install zsh-common
sudo apt install zsh-dev
sudo apt install zsh-doc
sudo apt install zsh-static
sudo apt install zsh-autosuggestions
sudo apt install zsh-syntax-highlighting
